services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: django-backend
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./media:/app/media
      - ./static:/app/staticfiles
    environment:
      - DEBUG=0
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    expose:
      - "8000"

  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-frontend
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    expose:
      - 3000

  nginx:
    image: nginx:latest
    container_name: nginx-server
    volumes:
      - ./media:/app/media
      - ./static:/app/staticfiles
      - ./frontend/build:/usr/share/nginx/html
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8099:80"
    depends_on:
      - backend
      - frontend
