# Generated by Django 5.1.4 on 2024-12-17 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PortfolioCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Название категории"
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория портфолио",
                "verbose_name_plural": "Категории портфолио",
            },
        ),
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название работы"),
                ),
                ("description", models.TextField(verbose_name="Описание работы")),
                (
                    "type",
                    models.CharField(
                        choices=[("photo", "Фото"), ("video", "Видео")],
                        max_length=10,
                        verbose_name="Тип работы",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="portfolio/images/",
                        verbose_name="Фото работы",
                    ),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="Ссылка на видео"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="works",
                        to="portfolio.portfoliocategory",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Работа портфолио",
                "verbose_name_plural": "Работы портфолио",
            },
        ),
    ]
