# Generated by Django 5.1.4 on 2024-12-17 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
        ("project_manager", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="client",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="portfolio_works",
                to="project_manager.client",
                verbose_name="Заказчик",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="portfolio",
            name="executors",
            field=models.ManyToManyField(
                related_name="portfolio_works",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Исполнители",
            ),
        ),
    ]
