# Generated by Django 5.1.4 on 2025-01-08 14:07

import config.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_portfolio_client_portfolio_executors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolio",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=config.storages.MediaStorage(),
                upload_to="portfolio/images/",
                verbose_name="Фото работы",
            ),
        ),
    ]
