# Generated by Django 5.1.4 on 2025-01-08 13:58

import config.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_service_detailed_description_service_video_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=config.storages.MediaStorage(),
                upload_to="services/",
                verbose_name="Изображение услуги",
            ),
        ),
    ]
