# Generated by Django 5.1.4 on 2024-12-17 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название заказчика"),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Email заказчика"),
                ),
                (
                    "phone",
                    models.CharField(max_length=20, verbose_name="Телефон заказчика"),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Адрес"
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказчик",
                "verbose_name_plural": "Заказчики",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название проекта"),
                ),
                ("description", models.TextField(verbose_name="Описание проекта")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Активный"),
                            ("completed", "Завершённый"),
                            ("on_hold", "Приостановленный"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Статус проекта",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Дата начала")),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата окончания"
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="project_manager.client",
                        verbose_name="Заказчик",
                    ),
                ),
                (
                    "executors",
                    models.ManyToManyField(
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Исполнители",
                    ),
                ),
            ],
            options={
                "verbose_name": "Проект",
                "verbose_name_plural": "Проекты",
            },
        ),
    ]
